# Generated by Django 6.0 on 2026-01-20 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Metrics Date')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Total Requests Processed')),
                ('successful_matches', models.PositiveIntegerField(default=0, verbose_name='Successful Matches')),
                ('accuracy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Accuracy Rate (%)')),
                ('average_response_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Avg Response Time (hours)')),
                ('top_1_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Top-1 Accuracy (%)')),
                ('top_3_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Top-3 Accuracy (%)')),
                ('top_5_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Top-5 Accuracy (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Metrics',
                'verbose_name_plural': 'AI Model Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AIRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Blood Compatibility Score')),
                ('distance_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distance Score')),
                ('responsiveness_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Responsiveness Score')),
                ('eligibility_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Eligibility Score')),
                ('final_rank_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Final Rank Score')),
                ('rank_position', models.PositiveIntegerField(verbose_name='Rank Position')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance (km)')),
                ('algorithm_version', models.CharField(default='1.0', max_length=20, verbose_name='Algorithm Version')),
                ('was_notified', models.BooleanField(default=False, verbose_name='Was Notified')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Ranking',
                'verbose_name_plural': 'AI Rankings',
                'ordering': ['blood_request', 'rank_position'],
            },
        ),
    ]
