# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('donors', '0001_initial'),
        ('requests_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airanking',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rankings', to='requests_management.bloodrequest'),
        ),
        migrations.AddField(
            model_name='airanking',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rankings', to='donors.donor'),
        ),
        migrations.AddIndex(
            model_name='airanking',
            index=models.Index(fields=['blood_request', 'rank_position'], name='ai_engine_a_blood_r_ffcfed_idx'),
        ),
        migrations.AddIndex(
            model_name='airanking',
            index=models.Index(fields=['calculated_at'], name='ai_engine_a_calcula_5b9db1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='airanking',
            unique_together={('blood_request', 'donor')},
        ),
    ]
