# Generated by Django 6.0 on 2026-02-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donor_status',
            field=models.CharField(blank=True, choices=[('DONOR_PENDING', 'Pending Approval'), ('DONOR_APPROVED', 'Approved'), ('DONOR_REJECTED', 'Rejected')], max_length=20, null=True, verbose_name='Donor Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='donor_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Donor Status Updated At'),
        ),
        migrations.AddField(
            model_name='user',
            name='donor_status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_status_updates', to=settings.AUTH_USER_MODEL, verbose_name='Donor Status Updated By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], default='user', max_length=20, verbose_name='User Type'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['donor_status'], name='users_user_donor_s_f4ae0e_idx'),
        ),
    ]
