# Generated by Django 6.0 on 2026-01-20 09:37

import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255, verbose_name='Hospital Name')),
                ('hospital_address', models.TextField(verbose_name='Hospital Address')),
                ('hospital_city', models.CharField(max_length=100, verbose_name='City')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[utils.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[utils.validators.validate_longitude])),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True, validators=[utils.validators.validate_phone_number], verbose_name='Emergency Contact')),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True, validators=[utils.validators.validate_phone_number], verbose_name='Secondary Contact')),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient Name')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor Name')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hospital Department')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['-created_at'],
            },
        ),
    ]
