# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['hospital_city'], name='recipients__hospita_64cdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['hospital_name'], name='recipients__hospita_60a922_idx'),
        ),
    ]
