# Generated by Django 6.0 on 2026-01-20 09:37

import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor Response',
                'verbose_name_plural': 'Donor Responses',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5, validators=[utils.validators.validate_blood_group], verbose_name='Required Blood Group')),
                ('units_required', models.PositiveIntegerField(validators=[utils.validators.validate_units], verbose_name='Units Required')),
                ('units_fulfilled', models.PositiveIntegerField(default=0, verbose_name='Units Fulfilled')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='Hospital Name')),
                ('hospital_address', models.TextField(verbose_name='Hospital Address')),
                ('hospital_city', models.CharField(max_length=100, verbose_name='City')),
                ('urgency_level', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20, verbose_name='Urgency Level')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Request Status')),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient Name')),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis/Reason')),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Attending Doctor')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Admin Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_matched_donors', models.ManyToManyField(blank=True, related_name='matched_requests', to='donors.donor', verbose_name='AI Matched Donors')),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
