# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0002_initial'),
        ('recipients', '0002_initial'),
        ('requests_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='recipients.recipient'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_responses', to='requests_management.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_responses', to='donors.donor'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group'], name='requests_ma_blood_g_258fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status'], name='requests_ma_status_50b3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['urgency_level'], name='requests_ma_urgency_19430a_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['hospital_city'], name='requests_ma_hospita_ec061d_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['requested_at'], name='requests_ma_request_c00283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donorresponse',
            unique_together={('blood_request', 'donor')},
        ),
    ]
