# Generated by Django 6.0 on 2026-02-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donorrequest'),
        ('requests_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='assigned_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='donors.donor', verbose_name='Assigned Donor'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Request Status'),
        ),
    ]
