# Generated by Django 6.0 on 2026-01-20 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], default='sms', max_length=20, verbose_name='Message Type')),
                ('message_content', models.TextField(verbose_name='Message Content')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject (for email)')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name='Delivery Status')),
                ('delivery_error', models.TextField(blank=True, null=True, verbose_name='Delivery Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Maximum Retries')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='External Message ID (Twilio SID etc.)')),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('no_response', 'No Response')], default='pending', max_length=20, verbose_name='Donor Response')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Response Timestamp')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('message_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], default='sms', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject Template')),
                ('content', models.TextField(help_text='Use {variable_name} for dynamic content', verbose_name='Message Template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
    ]
