# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('notifications', '0001_initial'),
        ('requests_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests_management.bloodrequest'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donors.donor'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['delivery_status'], name='notificatio_deliver_6a40be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['blood_request'], name='notificatio_blood_r_736259_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_01830a_idx'),
        ),
    ]
