# Generated by Django 6.0 on 2026-01-20 09:37

import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5)),
                ('units_donated', models.PositiveIntegerField(default=1, verbose_name='Units Donated')),
                ('donation_date', models.DateField(verbose_name='Donation Date')),
                ('next_eligible_date', models.DateField(verbose_name='Next Eligible Date')),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation History',
                'verbose_name_plural': 'Donation Histories',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5, validators=[utils.validators.validate_blood_group], verbose_name='Blood Group')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[utils.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[utils.validators.validate_longitude])),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='Last Donation Date')),
                ('donation_count', models.PositiveIntegerField(default=0, verbose_name='Total Donations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Donor')),
                ('is_eligible', models.BooleanField(default=True, verbose_name='Is Eligible to Donate')),
                ('response_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Response Rate (%)')),
                ('total_requests_received', models.PositiveIntegerField(default=0, verbose_name='Total Requests Received')),
                ('total_requests_accepted', models.PositiveIntegerField(default=0, verbose_name='Total Requests Accepted')),
                ('availability_status', models.BooleanField(default=True, verbose_name='Currently Available')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical History Notes')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CNIC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['-created_at'],
            },
        ),
    ]
