# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='donors.donor'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donors_dono_blood_g_e2a174_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['city'], name='donors_dono_city_452b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_active', 'is_eligible'], name='donors_dono_is_acti_7e3a91_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['latitude', 'longitude'], name='donors_dono_latitud_449b5c_idx'),
        ),
    ]
