# Generated by Django 6.0 on 2026-02-04 16:57

import django.db.models.deletion
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5, validators=[utils.validators.validate_blood_group], verbose_name='Blood Group')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[utils.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[utils.validators.validate_longitude])),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical History Notes')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True, verbose_name='CNIC')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Request Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_donor_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Request',
                'verbose_name_plural': 'Donor Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='donors_dono_status_524c36_idx'), models.Index(fields=['created_at'], name='donors_dono_created_9ec909_idx')],
            },
        ),
    ]
