# Generated by Django 6.0 on 2026-01-20 09:37

import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('addition', 'Stock Addition'), ('reservation', 'Reservation'), ('release', 'Release from Reservation'), ('fulfillment', 'Fulfillment'), ('expiry', 'Expiry'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('units', models.IntegerField(verbose_name='Units Changed')),
                ('units_before', models.PositiveIntegerField(verbose_name='Units Before')),
                ('units_after', models.PositiveIntegerField(verbose_name='Units After')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5, validators=[utils.validators.validate_blood_group], verbose_name='Blood Group')),
                ('units_available', models.PositiveIntegerField(default=0, verbose_name='Units Available')),
                ('units_reserved', models.PositiveIntegerField(default=0, verbose_name='Units Reserved')),
                ('units_expired', models.PositiveIntegerField(default=0, verbose_name='Units Expired (Total)')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='Hospital/Blood Bank Name')),
                ('hospital_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('hospital_city', models.CharField(max_length=100, verbose_name='City')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('minimum_threshold', models.PositiveIntegerField(default=10, verbose_name='Minimum Stock Threshold')),
                ('critical_threshold', models.PositiveIntegerField(default=5, verbose_name='Critical Stock Threshold')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blood Stock',
                'verbose_name_plural': 'Blood Stocks',
                'ordering': ['hospital_name', 'blood_group'],
                'indexes': [models.Index(fields=['blood_group'], name='blood_stock_blood_g_24d8ff_idx'), models.Index(fields=['hospital_city'], name='blood_stock_hospita_8ea285_idx'), models.Index(fields=['units_available'], name='blood_stock_units_a_018356_idx')],
                'unique_together': {('blood_group', 'hospital_name')},
            },
        ),
    ]
