# Generated by Django 6.0 on 2026-01-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_stock', '0001_initial'),
        ('requests_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='requests_management.bloodrequest'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='blood_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blood_stock.bloodstock'),
        ),
    ]
